catalog/urls.py
from django.urls import path

from catalog.views import (
    index,
    LiteraryFormatListView,
    BookListView,
    AuthorListView,
    BookDetailView,
    AuthorDetailView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,
    AuthorCreateView,
    BookCreateView,
    BookUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "literary-formats/",
        LiteraryFormatListView.as_view(),
        name="literary-format-list"
    ),
    path(
        "literary-formats/create/",
        LiteraryFormatCreateView.as_view(),
        name="literary-format-create"
    ),
    path(
        "literary-formats/<int:pk>/update/",
        LiteraryFormatUpdateView.as_view(),
        name="literary-format-update"
    ),
    path(
        "literary-formats/<int:pk>/delete/",
        LiteraryFormatDeleteView.as_view(),
        name="literary-format-delete"
    ),
    path(
        "books/",
        BookListView.as_view(),
        name="book-list"
    ),
    path(
        "books/<int:pk>/",
        BookDetailView.as_view(),
        name="book-detail",
    ),
    path(
        "books/create/",
        BookCreateView.as_view(),
        name="book-create"
    ),
    path(
        "books/<int:pk>/update/",
        BookUpdateView.as_view(),
        name="book-update"
    ),
    path(
        "autors/",
        AuthorListView.as_view(),
        name="author-list"
    ),
    path(
        "autors/create/",
        AuthorCreateView.as_view(),
        name="author-create"
    ),
    path(
        "autors/<int:pk>/",
        AuthorDetailView.as_view(),
        name="author-detail"
    )
]

app_name = "catalog"

library/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls",)),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Author(AbstractUser):
    pseudonym = models.CharField(max_length=63, null=True, blank=True)

    class Meta:
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("catalog:author-detail", args=[str(self.id)])


class Book(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=7, decimal_places=2)

    format = models.ForeignKey(
        LiteraryFormat,
        on_delete=models.CASCADE,
        related_name="books"
    )
    authors = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="writers")

    class Meta:
        ordering = ["title"]

    def get_absolute_url(self):
        return reverse("catalog:book-detail", args=[str(self.id)])

    def __str__(self):
        return f"{self.title} (price: {self.price}, format: {self.format.name})"

catalog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


from catalog.models import Author, Book


class AuthorCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Author
        fields = UserCreationForm.Meta.fields + ("pseudonym", "first_name", "last_name")


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Book
        fields = "__all__"


class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title"})
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from catalog.forms import AuthorCreationForm, BookForm, BookSearchForm
from catalog.models import Book, Author, LiteraryFormat


@login_required
def index(request):
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_literary_formats": num_literary_formats,
        "num_visits": num_visits + 1
    }

    return render(request, "catalog/index.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    fields = "__all__"
    template_name = "catalog/literary_format_form.html"
    success_url = reverse_lazy("catalog:literary-format-list")


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    template_name = "catalog/literary_format_form.html"
    success_url = reverse_lazy("catalog:literary-format-list")


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_confirm_delete.html"
    success_url = reverse_lazy("catalog:literary-format-list")


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.all().select_related("format")
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = BookSearchForm(initial={
            "title": title
        })

        return context

    def get_queryset(self):
        form = BookSearchForm(self.request.GET)

        if form.is_valid():
            return self.queryset.filter(
                title__icontains=form.cleaned_data["title"]
            )

        return self.queryset


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author

    success_url = reverse_lazy("registration:login")


class AuthorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Author
    form_class = AuthorCreationForm


class BookDetailView(generic.DetailView):
    model = Book


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm


templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  {% block title %}
    <title>Library</title>
  {% endblock %}
  <meta name="viewport" content="width-device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

  {%  load static %}
  <link rel="icon" href="{% static 'images/L-logo.png' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
      <div class="col-sm-10">
        {% block content %}{% endblock %}
        {% block pagination %}
          {% include "includes/pagination.html" %}
        {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

templates/catalog/author_detail.html
{% extends "base.html"%}

{% block content %}
  <h1>{{ author.first_name }} {{ author.last_name }}</h1>
  <p>Username: {{ author.username }}</p>

  <div class="ml-3">
    <h3>Books:</h3>

    {%  for book in author.writers.all %}
      <hr>
      <a href="{{ book.get_absolute_url }}"> {{ book.title}}</a>
    {% empty %}
      <p>No books!!!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/author_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Author</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Author list
    <a style="float: right" href="{% url 'catalog:author-create' %}" class="btn btn-primary">Add author</a>
  </h1>
  {% if author_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Full Name</th>
        <th>Username</th>
        <th>Pseudonym</th>
      </tr>

      {% for author in author_list %}
        <tr>
          <td>
            <a href="{{ author.get_absolute_url }}">{{ author.id }}</a>
          </td>
          <td>
            {{ author.first_name }} {{ author.last_name }}
          </td>
          <td>
            {{ author.username }}
          </td>
          <td>
            {{ author.pseudonym|default_if_none:"" }}
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no authors in library</p>
  {% endif %}
{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html"%}

{% block content %}
  <h1>Title: {{ book.title }}
    <a style="float: right" href="{% url 'catalog:book-update' pk=book.id %}" class="btn btn-secondary">Edit</a>
  </h1>
  <p><strong>Price:</strong> {{ book.price }}</p>
  <p><strong>Format:</strong> {{ book.format.name }}</p>

  <div class="ml-3">
    <h3>Authors</h3>

    {%  for author in book.authors.all %}
      <hr>
      <p class="text-muted"><strong>Id:</strong> {{  author.id }}</p>
      <p><strong>Full name:</strong> {{  author.first_name }} {{ author.last_name }}
      {% if author.pseudonym %} ({{ author.pseudonym }}){%  endif %}
      </p>
    {% empty %}
      <p>No authors!!!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Book</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Book list
    <a style="float: right" href="{% url 'catalog:book-create' %}" class="btn btn-primary link-to-page">
      Add book
    </a>
  </h1>

  <form action="" method="GET" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-secondary" value="🔎">
  </form>

  {% if book_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Price</th>
        <th>Format</th>
      </tr>

      {% for book in book_list %}
        <tr>
          <td>
            <a href="{{ book.get_absolute_url }}">{{ book.id }}</a>
          </td>
          <td>
            {{ book.title}}
          </td>
          <td>
            {{ book.price }}
          </td>
          <td>
            {{ book.format }}
          </td>
        </tr>
      {% endfor %}
    </table>
    {% else %}
      <p>There are no books in library</p>
    {% endif %}

{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Library Home</h1>
  <p>Welcome to Library</p>
  <h3>Library content:</h3>
  <ul>
    <li>Num books: {{ num_books }}</li>
    <li>Num authors: {{ num_authors }}</li>
    <li>Num literary formats: {{ num_literary_formats }}</li>
  </ul>
  <p>You have visited this page {{  num_visits }} time{{ num_visits|pluralize }}</p>
{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Literary Format</h1>

  <p>Are you sure you want to delete the literary format: {{ literaryformat }}?</p>
  <p><i>All books with this literary format will be also deleted</i></p>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-primary">
  </form>

{% endblock %}

templates/catalog/literary_format_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Literary Format</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Literary format list
    <a style="float: right" href="{% url 'catalog:literary-format-create' %}" class="btn btn-primary">Create new format</a>
  </h1>

  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for literary_format in literary_format_list %}
        <tr>
          <td>
            {{ literary_format.id }}
          </td>
          <td>
            {{ literary_format.name }}
          </td>
          <td>
            <a href="{% url 'catalog:literary-format-update' pk=literary_format.id %}">UPDATE</a>
          </td>
          <td>
            <a style="color: red" href="{% url 'catalog:literary-format-delete' pk=literary_format.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no literary formats in library</p>
  {% endif %}

{% endblock %}

templates/includes/pagination.html
{% load qery_transform %}
{% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
          </li>
        {% endif %}

        <li class="page-item active">
          <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
          <li class="page-item">
            <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
          </li>
        {% endif %}
      </ul>
    {% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {%  if user.is_authenticated %}
    <li class="list-group-item">User: {{ user.username }}</li>
    <li class="list-group-item"><a href="{% url 'logout' %}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
  {% endif %}

  <br>
  <li class="list-group-item"><a href="{% url 'catalog:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:author-list' %}">All authors</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:book-list' %}">All books</a></li>
  <li class="list-group-item"><a href="{% url 'catalog:literary-format-list' %}">All literary formats</a></li>
</ul>